import { EarthIcon, GiftIcon, ShareIcon } from "@/Components/Shared/Icons";
import { Fragment } from "react";
import Item from "./Item";
import HorizontalSeparatorLine from "./HorizontalSeparatorLine";
import { useMobile } from "@/hooks/useMobile";
interface ReferralProgramOverviewProps {
  activeSection: number;
  section: number;
}
const ReferralProgramOverview: React.FC<ReferralProgramOverviewProps> = ({
  activeSection,
  section,
}) => {
  const { isMobile } = useMobile();

  if (activeSection !== section && isMobile) return;
  return (
    <Fragment>
      <div className="px-[40px] flex flex-col gap-[15px]">
        <p className="text-[#222222] text-xl font-normal">
          Share and Earn! 🚀✨
        </p>
        <p className="text-[#87878D] text-[15px] font-normal">
          Invite your friends and neighbours to SkyTrade. If they register and
          claim airspaces, you receive:
        </p>
        <p className="text-[#4285F4] text-[15px] font-normal">
          <span className="font-bold text-[20px]">+5 SKY points to you</span> for
          each successful referral registration and{" "}
          <span className="font-bold text-[20px]">+5 SKY points</span> to the
          successfully referred person
          <br />
          <span className="font-bold text-[20px]">+10%</span> on top of the
          passive income generated by those you refer{" "}
          <span className="font-bold text-[20px]">FOREVER</span>
        </p>
      </div>
      <div className="flex flex-col md:flex-row items-center justify-center gap-4 md:gap-9 px-[35px] md:px-[51px]">
        <Item
          icon={<ShareIcon color={undefined} />}
          title={"Share"}
          text={
            "Send your invite link or code to your friends and explain them how cool is SkyTrade"
          }
        />
        <HorizontalSeparatorLine />
        <Item
          icon={<EarthIcon isActive={true} />}
          title={"Register & Claim"}
          text={
            "Let them register and claim their airspaces using your referral link or code"
          }
        />
        <HorizontalSeparatorLine />
        <Item
          icon={<GiftIcon isActive={true} />}
          title={"Earn"}
          text={"You and your friends are rewarded with 5 SKY points and more"}
        />
      </div>
    </Fragment>
  );
};
export default ReferralProgramOverview;